sudo: false
language: perl
perl:
  - "5.14"
addons:
  apt:
    packages:
    - libdb-dev
    - libgd2-noxpm-dev
    - nginx
install:
  - cpanm --notest -L extlib/ GD::Image URI::Escape
  - cpanm --notest -l extlib/ git://github.com/bioperl/bioperl-live.git@v1.6.x
  - bash setup.sh
  - npm install -g jshint
  - cat tests/travis.conf | envsubst > tests/travis-envsubst.conf
  - nginx -c tests/travis-envsubst.conf
script:
  - node src/dojo/dojo.js load=build --require "src/JBrowse/init.js" --profile "src/JBrowse/JBrowse.profile.js"
  - prove -Isrc/perl5 -lr tests
  - phantomjs tests/js_tests/run-jasmine.js http://localhost:9000/tests/js_tests
  - jshint src/JBrowse/

after_failure: cat setup.log 
