language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  - cpanm PerlIO::gzip
  - cpanm GD::Image 
  - ./setup.sh

install: true

script:
  - prove -I src/perl5 -r tests/perl_tests

