language: perl
perl:
  - "5.14"

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libpng-dev zlib1g-dev libgd2-xpm-dev
  - sudo apt-get install libdb-dev 
  - cpanm -l extlib/ PerlIO::gzip
  - cpanm -l extlib/ GD::Image
  - cpanm -l extlib/ DBI DB_File Data::Stag
  - cpanm -l extlib/ URI::Escape 
  - ./setup.sh
  - ls -l /home/travis/build/cmdcolin/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/5.14.2
  - ls -l /home/travis/build/cmdcolin/jbrowse/bin/../src/perl5/../../extlib/lib/perl5
  - ls -l /home/travis/build/cmdcolin/jbrowse/bin/../src/perl5
  - ls -l /home/travis/build/cmdcolin/jbrowse/src/perl5/../../extlib/lib/perl5

script:
  - prove -I src/perl5 -r tests/perl_tests

after_failure: cat /home/travis/.cpanm/work/*/build.log 
