language: perl
perl:
  - "5.14"

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libpng-dev zlib1g-dev libgd2-xpm-dev
  - sudo apt-get install libdb-dev 
  - wget -O release-1-6-922.zip https://github.com/bioperl/bioperl-live/archive/release-1-6-922.zip
  - unzip release-1-6-922.zip
  - cd bioperl-live-release-1-6-922/
  - perl Build.PL --accept
  - ./Build
  - sudo ./Build install
  - cd ..
  - cpanm --self-contained -l extlib/ PerlIO::gzip
  - cpanm --self-contained -l extlib/ GD::Image
  - cpanm --self-contained -l extlib/ DBI DB_File Data::Stag
  - cpanm --self-contained -l extlib/ URI::Escape 
  - ./setup.sh
  - ls -l /home/travis/build/cmdcolin/jbrowse/extlib/lib/perl5
install: true
script:
  - prove -I src/perl5 -r tests/perl_tests

after_failure: cat setup.log 
