language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libpng-dev zlib1g-dev libgd2-xpm-dev
  - sudo apt-get install libdb-dev 
  - bin/cpanm -v --notest -l extlib/ --installdeps PerlIO::gzip
  - bin/cpanm -v --notest -l extlib/ --installdeps  GD::Image
  - bin/cpanm -v --notest -l extlib/ --installdeps  DBI DB_File Data::Stag
  - bin/cpanm -v --notest -l extlib/ --installdeps  URI::Escape 
  - ./setup.sh

install: true

script:
  - prove -I src/perl5 -r tests/perl_tests

after_failure: cat /home/travis/.cpanm/work/*/build.log 
