language: perl
perl:
  - "5.14"

before_install:
  - cpanm --notest git://github.com/bioperl/bioperl-live.git@v1.6.x
  - ./setup.sh
install: true
script:
  - prove -I src/perl5 -r tests/perl_tests

after_failure: cat setup.log 
