language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
  - ./setup.sh

install: true

script:
  - make -f build/Makefile release

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#gmod"
