language: perl
perl:
  - "5.14"

install:
  - sudo apt-get install libdb-dev libgd2-noxpm-dev
  - cpanm --notest -L extlib/ GD::Image URI::Escape
  - cpanm --notest -l extlib/ git://github.com/bioperl/bioperl-live.git@v1.6.x
  - bash setup.sh
  - npm install -g http-server
script:
  - http-server -p 9000 &
  - prove -Isrc/perl5 -lr tests
  - phantomjs tests/js_tests/run-jasmine.js http://localhost:9000/ 

after_failure: cat setup.log 
