sudo: false
language: perl
perl:
  - "5.14"
addons:
  apt:
    packages:
    - libdb-dev
    - libgd2-noxpm-dev
install:
  - cpanm --notest GD::Image URI::Escape
  - cpanm --notest git://github.com/bioperl/bioperl-live.git@v1.6.x
  - bash setup.sh
  - npm install -g http-server jshint
script:
  - node src/dojo/dojo.js load=build --require "src/JBrowse/init.js" --profile "src/JBrowse/JBrowse.profile.js"
  - nohup http-server -p 9000 2>&1 &
  - prove -Isrc/perl5 -lr tests
  - phantomjs tests/js_tests/run-jasmine.js http://localhost:9000/tests/js_tests
  - jshint src/JBrowse/
  - make -f build/Makefile release

after_failure: cat setup.log 
